import CA10192 from '../../assets/casas-arranhadores/10192.png';
import CA10193 from '../../assets/casas-arranhadores/10193.png';
import CA10195 from '../../assets/casas-arranhadores/10195.png';
import CA10196 from '../../assets/casas-arranhadores/10196.png';
import CA10198 from '../../assets/casas-arranhadores/10198.png';
import CA10200 from '../../assets/casas-arranhadores/10200.png';
import CA10202 from '../../assets/casas-arranhadores/10202.png';
import CA10203 from '../../assets/casas-arranhadores/10203.png';
import CA10213 from '../../assets/casas-arranhadores/10213.png';
import CA10214 from '../../assets/casas-arranhadores/10214.png';
import CA10215 from '../../assets/casas-arranhadores/10215.png';
import CA10216 from '../../assets/casas-arranhadores/10216.png';
import CA10218 from '../../assets/casas-arranhadores/10218.png';
import CA10219 from '../../assets/casas-arranhadores/10219.png';
import CA10220 from '../../assets/casas-arranhadores/10220.png';
import CA10222 from '../../assets/casas-arranhadores/10222.png';
import CA10223 from '../../assets/casas-arranhadores/10223.png';
import CA10224 from '../../assets/casas-arranhadores/10224.png';
import CA10225 from '../../assets/casas-arranhadores/10225.png';
import CA10230 from '../../assets/casas-arranhadores/10230.png';
import CA10231 from '../../assets/casas-arranhadores/10231.png';
import CA10232 from '../../assets/casas-arranhadores/10232.png';
import CA10233 from '../../assets/casas-arranhadores/10233.png';
import CA10234 from '../../assets/casas-arranhadores/10234.png';
import CA10235 from '../../assets/casas-arranhadores/10235.png';
import CA10236 from '../../assets/casas-arranhadores/10236.png';
import CA10237 from '../../assets/casas-arranhadores/10237.png';
import CA10238 from '../../assets/casas-arranhadores/10238.png';
import CA10239 from '../../assets/casas-arranhadores/10239.png';
import CA10240 from '../../assets/casas-arranhadores/10240.png';
import CA10241 from '../../assets/casas-arranhadores/10241.png';
import CA10242 from '../../assets/casas-arranhadores/10242.png';
import CA10243 from '../../assets/casas-arranhadores/10243.png';
import CA10244 from '../../assets/casas-arranhadores/10244.png';
import CA10245 from '../../assets/casas-arranhadores/10245.png';
import CA10246 from '../../assets/casas-arranhadores/10246.png';
import CA10247 from '../../assets/casas-arranhadores/10247.png';
import CA10248 from '../../assets/casas-arranhadores/10248.png';
import CA10249 from '../../assets/casas-arranhadores/10249.png';
import CA10250 from '../../assets/casas-arranhadores/10250.png';
import CA10251 from '../../assets/casas-arranhadores/10251.png';
import CA10981 from '../../assets/casas-arranhadores/10981.png';
import CA10983 from '../../assets/casas-arranhadores/10983.png';
import CA10984 from '../../assets/casas-arranhadores/10984.png';
import CA10985 from '../../assets/casas-arranhadores/10985.png';
import CA10291 from '../../assets/casas-arranhadores/10291.png';
import CA10292 from '../../assets/casas-arranhadores/10292.png';
import CA10293 from '../../assets/casas-arranhadores/10293.png';
import CA10295 from '../../assets/casas-arranhadores/10295.png';
import CA10296 from '../../assets/casas-arranhadores/10296.png';
//======================================================================================================//

//======================================================================================================//
import BR10177 from '../../assets/brinquedos-acessorios/10177.png';
import BR10176 from '../../assets/brinquedos-acessorios/10176.png';
import BR10280 from '../../assets/brinquedos-acessorios/10280.png';
import BR10281 from '../../assets/brinquedos-acessorios/10281.png';
import BR10282 from '../../assets/brinquedos-acessorios/10282.png';
import BR10283 from '../../assets/brinquedos-acessorios/10283.png';
import BR10175 from '../../assets/brinquedos-acessorios/10175.png';
import BR10284 from '../../assets/brinquedos-acessorios/10284.png';
import BR10174 from '../../assets/brinquedos-acessorios/10174.png';
import BR10285 from '../../assets/brinquedos-acessorios/10285.png';
import BR10286 from '../../assets/brinquedos-acessorios/10286.png';
import BR10287 from '../../assets/brinquedos-acessorios/10287.png';
import PM1704 from '../../assets/brinquedos-acessorios/PM1704.png';
import PM2335 from '../../assets/brinquedos-acessorios/pm2335.png';
import OB1108 from '../../assets/brinquedos-acessorios/ob1108.png';
import OB1109 from '../../assets/brinquedos-acessorios/ob1109.png';
// import PM1082 from '../../assets/brinquedos-acessorios/pm1082.png';
// import PM1083 from '../../assets/brinquedos-acessorios/pm1083.png';
// import PM1424 from '../../assets/brinquedos-acessorios/pm1424.png';
// import PM3668 from '../../assets/brinquedos-acessorios/pm3668.png';
import PM1577 from '../../assets/brinquedos-acessorios/PM1577.png';
import PM1086 from '../../assets/brinquedos-acessorios/PM1086.png';
import PM1704X from '../../assets/brinquedos-acessorios/PM1704X.png';
import C2232 from '../../assets/brinquedos-acessorios/C2232.png';
import C2231 from '../../assets/brinquedos-acessorios/C2231.png';
import C2229 from '../../assets/brinquedos-acessorios/C2229.png';
import C2130 from '../../assets/brinquedos-acessorios/C2130.png';
import C2163 from '../../assets/brinquedos-acessorios/C2163.png';
import BR10175XX from '../../assets/brinquedos-acessorios/10175XX.png';
import C2225 from '../../assets/brinquedos-acessorios/C2225.png';
import C2225X from '../../assets/brinquedos-acessorios/C2225X.png';
import C2226 from '../../assets/brinquedos-acessorios/C2226.png';
import C2223 from '../../assets/brinquedos-acessorios/C2223.png';
import C2224 from '../../assets/brinquedos-acessorios/C2224.png';
import C2227 from '../../assets/brinquedos-acessorios/C2227.png';
import C2067 from '../../assets/brinquedos-acessorios/C2067.png';
import C2230 from '../../assets/brinquedos-acessorios/C2230.png';
import S5090 from '../../assets/brinquedos-acessorios/S5090.png';
import C2203 from '../../assets/brinquedos-acessorios/c2203.png';
import PM2267 from '../../assets/brinquedos-acessorios/PM2267.png';
import BR10281X from '../../assets/brinquedos-acessorios/10281X.png';
import EI21 from '../../assets/brinquedos-acessorios/EI21.png';
import BR10288 from '../../assets/brinquedos-acessorios/10288.png';
import BR10175X from '../../assets/brinquedos-acessorios/10175X.png';
import UZ42 from '../../assets/brinquedos-acessorios/Uz42.png';
//======================================================================================================//

//======================================================================================================//
import CO1 from '../../assets/brinquedos-acessorios/comedouroOsso1L/CO_1.png';
import CO2 from '../../assets/brinquedos-acessorios/comedouroOsso1L/CO_2.png';
import CO3 from '../../assets/brinquedos-acessorios/comedouroOsso1L/CO_3.png';
import CO4 from '../../assets/brinquedos-acessorios/comedouroOsso1L/CO_4.png';
import CO5 from '../../assets/brinquedos-acessorios/comedouroOsso1L/CO_5.png';
import CO6 from '../../assets/brinquedos-acessorios/comedouroOsso1L/CO_6.png';
//======================================================================================================//

//======================================================================================================//
import CC1 from '../../assets/brinquedos-acessorios/comedouroClassic200ML/CC_1.png';
import CC2 from '../../assets/brinquedos-acessorios/comedouroClassic200ML/CC_2.png';
import CC3 from '../../assets/brinquedos-acessorios/comedouroClassic200ML/CC_3.png';
import CC4 from '../../assets/brinquedos-acessorios/comedouroClassic200ML/CC_4.png';
import CC5 from '../../assets/brinquedos-acessorios/comedouroClassic200ML/CC_5.png';
import CC6 from '../../assets/brinquedos-acessorios/comedouroClassic200ML/CC_6.png';
import CC7 from '../../assets/brinquedos-acessorios/comedouroClassic200ML/CC_7.png';
import CC8 from '../../assets/brinquedos-acessorios/comedouroClassic200ML/CC_8.png';
//======================================================================================================//

//======================================================================================================//
export const products =[
//======================================================================================================//
    [
        {
            imag:CA10230,
            title:"Arranhador Barril",
            line_1:"Material: MDF,pelúcia,sisal e manta de juta",
            line_2:"(C:40)x(L:40)x(A:49)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00001#001",
            code:"Cód_10230",
            line_6:"1x Arranhador Barril",
            a2:"não necessita montagem",
            value:191.55,
        },
        {
            imag:CA10214,
            title:"Arranhador Berlim",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:48)x(L:48)x(A:120)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00002#001",
            code:"Cód_10214",
            line_6:"1x Arranhador Berlim",
            a2:"1x manual de instruções",
            value:260.51,
        },
        {
            imag:CA10231,
            title:"Arranhador Barril Duplo",
            line_1:"Material: MDF,pelúcia,sisal e manta de juta",
            line_2:"(C:40)x(L:40)x(A:74)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00003#002",
            code:"Cód_10231",
            line_6:"1x Arranhador Barril Duplo",
            a2:"não necessita montagem",
            value:237.27,
        },
        {
            imag:CA10216,
            title:"Arranhador Cairo",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:34)x(L:98)x(A:45)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00004#002",
            code:"Cód_10216",
            line_6:"1x Arranhador Cairo",
            value:204.10,
        },
        {
            imag:CA10224,
            title:"Arranhador Castelo",
            line_1:"Material: MDF,pelúcia,sisal e manta de juta",
            line_2:"(C:75)x(L:39)x(A:104)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00005#003",
            code:"Cód_10224",
            line_6:"1x Arranhador castelo para gato",
            value:360.59,
        },
        {
            imag:CA10222,
            title:"Arranhador Luanda",
            line_1:"Material: MDF,pelúcia,sisal e manta de juta",
            line_2:"(C:40)x(L:48)x(A:120)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00006#003",
            code:"Cód_10222",
            line_6:"1x Arranhador Luanda",
            value:240.67,   
        },
        {
            imag:CA10218,
            title:"Arranhador Duas Casas",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:36)x(L:55)x(A:59)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00007#004",
            code:"Cód_10218",
            line_6:"1x Arranhador Duas Casas",
            value:249,   
        },
        {
            imag:CA10233,
            title:"Arranhador Castelo com Torre",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:85)x(L:70)x(A:115)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00008#004",
            code:"Cód_10233",
            line_6:"1x Arranhador Castelo com Torre",
            value:379.31,   
        },
        {
            imag:CA10232,
            title:"Arranhador Houston",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:30)x(L:50)x(A:80)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00009#005",
            code:"Cód_10232",
            line_6:"1x Arranhador Houston",
            value:142.50,   
        },
        {
            imag:CA10223,
            title:"Arranhador Madrid",
            line_1:"Material: MDF,pelúcia,sisal e manta de juta",
            line_2:"(C:60)x(L:40)x(A:81)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00010#005",
            code:"Cód_10223",
            line_6:"1x Arranhador Madrid",
            value:203.70,   
        },
        {
            imag:CA10215,
            title:"Arranhador Montevidéo",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:35)x(L:48)x(A:100)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00011#006",
            code:"Cód_10215",
            line_6:"1x Arranhador Montevidéo",
            value:213.36,   
        },
        {
            imag:CA10225,
            title:"Arranhador Topázio",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:30)x(L:41)x(A:58)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00012#006",
            code:"Cód_10225",
            line_6:"1x Arranhador Topázio",
            value:123.84,   
        },
        {
            imag:CA10234,
            title:"Arranhador Irwin",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:58)x(L:48)x(A:110)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00013#007",
            code:"Cód_10234",
            line_6:"1x Arranhador Irwin",
            value:353.75,   
        },
        {
            imag:CA10219,
            title:"Arranhador Vênus",
            line_1:"Material: MDF,pelúcia,sisal e manta de juta",
            line_2:"(C:30)x(L:30)x(A:50)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00014#007",
            code:"Cód_10219",
            line_6:"1x Arranhador Vênus",
            value:89.51,   
        },
        {
            imag:CA10220,
            title:"Arranhador Turin",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:36)x(L:55)x(A:59)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00015#008",
            code:"Cód_10220",
            line_6:"1x Arranhador Turin",
            value:164.85,   
        },
        {
            imag:CA10235,
            title:"Arranhador Napoles ",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:58)x(L:48)x(A:110)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00016#008",
            code:"Cód_10235",
            line_6:"1x Arranhador Napoles",
            value:459.81,   
        },
        {
            imag:CA10236,
            title:"Arranhador Ninho ",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:60)x(L:60)x(A:93)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x28Cm",
            line_4:"Diâmetro do orificio circular do interior: 22Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00017#009",
            code:"Cód_10236",
            line_6:"1x Arranhador Ninho",
            value:168.38,   
        },
        {
            imag:CA10981,
            title:"Arranhador Olimpus ",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:60)x(L:50)x(A:120)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 40x30Cm",
            line_4:"Diâmetro do orificio circular do interior: 22Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00018#009",
            code:"Cód_10981",
            line_6:"1x Arranhador Olimpus",
            value:283.76,   
        }, 
        {
            imag:CA10213,
            title:"Arranhador Aconchego ",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:30)x(L:40)x(A:60)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 22Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00019#010",
            code:"Cód_10213",
            line_6:"1x Arranhador Aconchego",
            value:139.24,   
        }, 
        {
            imag:CA10237,
            title:"Arranhador Kioto ",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:30)x(L:40)x(A:60)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00020#010",
            code:"Cód_10237",
            line_6:"1x Arranhador Kioto",
            value:242.28,   
        },
        {
            imag:CA10984,
            title:"Arranhador Tokyo ",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:50)x(L:50)x(A:100)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00021#011",
            code:"Cód_10984",
            line_6:"1x Arranhador Tokyo",
            value:254.90,   
        },      
        {
            imag:CA10195,
            title:"Arranhador Buzios ",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:50)x(L:50)x(A:100)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00022#011",
            code:"Cód_10195",
            line_6:"1x Arranhador Buzios",
            value:219.25,   
        },
        {
            imag:CA10238,
            title:"Arranhador Tunisia ",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:50)x(L:70)x(A:114)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00023#012",
            code:"Cód_10238",
            line_6:"1x Arranhador Tunisia",
            value:406.89,   
        },       
        {
            imag:CA10239,
            title:"Arranhador Bangkok ",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:48)x(L:48)x(A:100)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00024#012",
            code:"Cód_10239",
            line_6:"1x Arranhador Bangkok",
            value:300.16,   
        },       
        {
            imag:CA10240,
            title:"Arranhador Catedral",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:48)x(L:48)x(A:104)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00025#013",
            code:"Cód_10240",
            line_6:"1x Arranhador Catedral",
            value:304.74,   
        },
        {
            imag:CA10241,
            title:"Arranhador Tirruana",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:73)x(L:48)x(A:50)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00026#013",
            code:"Cód_10241",
            line_6:"1x Arranhador Tirruana",
            value:143.40,   
        },
        {
            imag:CA10242,
            title:"Arranhador Jumping",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:39)x(L:39)x(A:114)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00027",
            code:"Cód_10242",
            line_6:"1x Arranhador Jumping",
            value:304.74,   
        },
        {
            imag:CA10196,
            title:"Arranhador Boston",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:30)x(L:40)x(A:60)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 30Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00028",
            code:"Cód_10196",
            line_6:"1x Arranhador Boston",
            value:141.09,   
        },
        {
            imag:CA10243,
            title:"Arranhador Lisboa",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:39)x(L:39)x(A:114)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00029",
            code:"Cód_10243",
            line_6:"1x Arranhador Lisboa",
            value:200.52,   
        }, 
        {
            imag:CA10244,
            title:"Arranhador Tunel",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:35)x(L:60)x(A:55)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 20Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00030",
            code:"Cód_10244",
            line_6:"1x Arranhador Tunel",
            value:158.86,   
        }, 
        {
            imag:CA10245,
            title:"Arranhador Casa Coqueiro",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:40)x(L:55)x(A:89)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x17Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00031",
            code:"Cód_10245",
            line_6:"1x Arranhador Casa Coqueiro",
            value:284.38,   
        },     
        {
            imag:CA10246,
            title:"Arranhador Casinha",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:35)x(L:60)x(A:45)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 30Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00032",
            code:"Cód_10246",
            line_6:"1x Arranhador Casinha",
            value:182.87,   
        },
        {
            imag:CA10247,
            title:"Arranhador Barcelona",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:41)x(L:70)x(A:112)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00033",
            code:"Cód_10247",
            line_6:"1x Arranhador Barcelona",
            value:264.16,   
        },
        {
            imag:CA10248,
            title:"Arranhador Torre",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:45)x(L:45)x(A:91)Cm",
            line_3:"Diâmetro dos orifícios exteriores: Não possui",
            line_4:"Diâmetro da cama circular superior: 35*45Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00034",
            code:"Cód_10247",
            line_6:"1x Arranhador torre",
            value:127.57,   
        },
        {
            imag:CA10192,
            title:"Arranhador Peruibe",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:40)x(L:40)x(A:50)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 40x20Cm",
            line_4:"Diâmetro da cama superior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00035",
            code:"Cód_10192",
            line_6:"1x Arranhador Peruibe",
            value:77.48,   
        },
        {
            imag:CA10249,
            title:"Arranhador Escada Com Toca",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:35)x(L:60)x(A:45)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 30Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00036",
            code:"Cód_10249",
            line_6:"1x Arranhador Escada Com Toca",
            value:256.47,   
        },
        {
            imag:CA10193,
            title:"Arranhador Atalanta",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:41)x(L:70)x(A:112)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00037",
            code:"Cód_10193",
            line_6:"1x Arranhador Atalanta",
            value:79.13,   
        }, 
        {
            imag:CA10250,
            title:"Arranhador Nikko",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:43)x(L:39)x(A:50)Cm",
            line_3:"Diâmetro dos orifícios exteriores: Não Possui",
            line_4:"Diâmetro das bases elevadas: 35Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00038",
            code:"Cód_10250",
            line_6:"1x Arranhador Nikko",
            value:120.73,   
        }, 
        {
            imag:CA10203,
            title:"Arranhador Oklahoma",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:30)x(L:50)x(A:80)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro da cama suspensa: 30Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00039",
            code:"Cód_10203",
            line_6:"1x Arranhador Oklahoma",
            value:200.89,   
        },
        {
            imag:CA10251,
            title:"Bogotá",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:40)x(L:40)x(A:60)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro da cama suspensa: 30Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00040",
            code:"Cód_10251",
            line_6:"1x Arranhador Bogotá",
            value:148.92,   
        },
        {
            imag:CA10198,
            title:"Arranhador Patinhas",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:40)x(L:40)x(A:50)Cm",
            line_3:"Diâmetro dos orifícios exteriores: Não Possui",
            line_4:"Diâmetro da cama suspensa: 40Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00041",
            code:"Cód_10198",
            line_6:"1x Arranhador Patinhas",
            value:73.30,   
        },
        {
            imag:CA10983,
            title:"Arranhador Chicago",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:36)x(L:60)x(A:120)Cm",
            line_3:"Diâmetro dos orifícios exteriores: Não Possui",
            line_4:"Diâmetro da cama suspensa: 22Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00042",
            code:"Cód_10983",
            line_6:"1x Arranhador Chicago",
            value:183.49,   
        },       
        {
            imag:CA10200,
            title:"Arranhador Burj Khalifa",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:40)x(L:60)x(A:170)Cm",
            line_3:"Diâmetro dos orifícios exteriores: Não Possui",
            line_4:"Diâmetro da casa superior: 40Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00043",
            code:"Cód_10200",
            line_6:"1x Arranhador Burj Khalifa",
            value:540.09,   
        },
        {
            imag:CA10985,
            title:"Arranhador Haren",
            line_1:"",
            line_2:"",
            line_3:"",
            line_4:"",
            line_5:"Sem informações",
            id:"Núm_00044",
            code:"Cód_10985",
            line_6:"1x Arranhador Haren",
            value:674.62,   
        },
        {
            imag:CA10202,
            title:"Arranhador Londres",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:120)x(L:50)x(A:180)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 35Cm",
            line_4:"Diâmetro da toquinha: 40Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00045",
            code:"Cód_10202",
            line_6:"1x Arranhador Londres",
            value:1015.85,   
        },
        {
            imag:CA10291,
            title:"Canto de Sofá Sisal Roxo",
            line_2:"(C:30)x(L:30)x(A:50)Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00046",
            code:"Cód_10291",
            line_6:"1x Canto de Sofá Roxo",
            value:39.90,   
        },
        {
            imag:CA10292,
            title:"Canto de Sofá Sisal Rosa Bebê",
            line_2:"(C:30)x(L:30)x(A:50)Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00047",
            code:"Cód_10292",
            line_6:"1x Canto de Sofá Rosa Bebê",
            value:39.90,   
        },
        {
            imag:CA10293,
            title:"Canto de Sofá Sisal Azul Royal",
            line_2:"(C:30)x(L:30)x(A:50)Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00048",
            code:"Cód_10293",
            line_6:"1x Canto de Sofá Azul Royal",
            value:39.90,   
        },
        {
            imag:'',
            title:"Canto de Sofá Carpete Azul Royal",
            line_2:"(C:30)x(L:30)x(A:50)Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00049",
            code:"Cód_10294",
            line_6:"1x Canto de Sofá Azul Royal",
            value:39.90,   
        },
        {
            imag:CA10295,
            title:"Canto de Sofá Sisal Vermelho",
            line_2:"(C:30)x(L:30)x(A:50)Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00050",
            code:"Cód_10295",
            line_6:"1x Canto de Sofá Vermelho",
            value:39.90,   
        },
        {
            imag:CA10296,
            title:"Canto de Sofá Sisal Marrom",
            line_2:"(C:30)x(L:30)x(A:50)Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00051",
            code:"Cód_10296",
            line_6:"1x Canto de Sofá Marrom",
            value:39.90,   
        },
        {
            imag:'',
            title:"Canto de Sofá Carpete Marrom",
            line_2:"(C:30)x(L:30)x(A:50)Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00052",
            code:"Cód_10297",
            line_6:"1x Canto de Sofá Marrom",
            value:39.90,   
        },
    ],
//======================================================================================================//

//======================================================================================================//
    [
        {
            imag:BR10177,
            title: "Varinha de penas",
            id:"Núm_00125",
            code:"Cód_10177",
            line_2:"35Cm",
            line_6:"1x Varinha de penas",
            value: 5.90,
        },
        {
            imag:BR10176,
            title: "Varinha Ping Penas",
            id:"Núm_00126",
            code:"Cód_10176",
            line_2:"35Cm",
            line_6:"1x Varinha ping penas",
            value: 5.90,
        },
        {
            imag:BR10280,
            title: "Varinha Bolinha de Guizo com Penas",
            id:"Núm_00127",
            code:"Cód_10280",
            line_2:"35Cm",
            line_6:"1x Varinha bolinha de guizo com penas",
            value: 5.90,
        },
        {
            imag:BR10281,
            title: "Varinha Borboleta",
            id:"Núm_00128",
            code:"Cód_10281",
            line_2:"35Cm",
            line_6:"1x Varinha borboleta",
            value: 8.90,
        },
        {
            imag:BR10282,
            title: "Varinha Bolinha de Guizo com Pelúcia",
            id:"Núm_00129",
            code:"Cód_10282",
            line_2:"35Cm",
            line_6:"1x Varinha bolinha de guizo com pelúcia",
            value: 6.90,
        },
        {
            imag:BR10283,
            title: "Varinha Bolinha com Pelúcia",
            id:"Núm_00130",
            code:"Cód_10283",
            line_2:"35Cm",
            line_6:"1x Varinha bolinha com pelúcia",
            value: 6.90,
        },
        {
            imag:BR10175,
            title: "Varinha com Pelúcia",
            id:"Núm_00131",
            code:"Cód_10175",
            line_2:"35Cm",
            line_6:"1x Varinha com Pelúcia",
            value: 5.90,
        },
        {
            imag:BR10284,
            title: "Varinha com Ratinho + Penas",
            id:"Núm_00132",
            code:"Cód_10284",
            line_2:"35Cm",
            line_6:"1x Varinha com Ratinho + Penas",
            value: 8.90,
        },
        {
            imag:BR10174,
            title: "Varinha com Rolinho de Sisal",
            id:"Núm_00133",
            code:"Cód_10174",
            line_2:"35Cm",
            line_6:"1x Varinha com Rolinho de Sisal",
            value: 5.90,
        },
        {
            imag:BR10285,
            title: "Varinha Pom Pom + Penas",
            id:"Núm_00134",
            code:"Cód_10285",
            line_2:"35Cm",
            line_6:"1x Varinha Pom Pom + Penas",
            value: 8.90,
        },
        {
            imag:BR10286,
            title: "Varinha Rabo de Pelúcia",
            id:"Núm_00135",
            code:"Cód_10286",
            line_2:"35Cm",
            line_6:"1x Varinha Rabo de Pelúcia",
            value: 5.90,
        },
        {
            imag:BR10287,
            title: "Varinha Ratinho + Penas",
            id:"Núm_00136",
            code:"Cód_10287",
            line_2:"35Cm",
            line_6:"1x Varinha Ratinho + Penas",
            value: 7.90,
        },
        {
            imag:PM1704,
            title: "Dispenser Toy",
            id:"Núm_00137",
            code:"Cód_PM1704",
            line_2:"35Cm",
            line_6:"1x Dispenser Toy",
            value: 24.25,
        },
        {
            imag:PM2335,
            title: "Balance Cat",
            id:"Núm_00138",
            code:"Cód_PM2335",
            line_2:"35Cm",
            line_6:"1x Balance Cat",
            value: 21.58,
        },
        {
            imag:PM2267,
            title: "Varinha Bolinha de Guizo com Penas",
            id:"Núm_00139",
            code:"Cód_PM2267",
            line_2:"35Cm",
            line_6:"1x Varinha Bolinha de Guizo com Penas",
            value: 21.58,
        },
        {
            imag:BR10281X,
            title: "Bastão de Sisal",
            id:"Núm_00140",
            code:"Cód_10281",
            line_2:"35Cm",
            line_6:"1x Bastão de Sisal",
            value: 9.95,
        },
        {
            imag:BR10288,
            title: "Ping Penas",
            id:"Núm_00141",
            code:"Cód_10288",
            line_2:"35Cm",
            line_6:"1x Ping Penas",
            value: 1.99,
        },
        {
            imag:EI21,
            title: "Bola Corda Nó, não saborizada",
            id:"Núm_00142",
            code:"Cód_EI21",
            line_2:"35Cm",
            line_6:"1x Bola Corda Nó, não saborizada",
            value: 7.68,
        },
        {
            imag:BR10175X,
            title: "Varinha com Pelúcia",
            id:"Núm_00143",
            code:"Cód_10175",
            line_2:"35Cm",
            line_6:"1x Varinha com Pelúcia",
            value: 14.90,
        },
        {
            imag:C2225,
            title: "Kit Bolinha Flick com Guizo",
            id:"Núm_00144",
            code:"Cód_C2225",
            line_2:"35Cm",
            line_6:"1x Kit Bolinha Flick com Guizo",
            value: 4.90,
        },
        {
            imag:C2226,
            title: "Kit Bolinha Pic com Guizo",
            id:"Núm_00145",
            code:"Cód_C2226",
            line_2:"35Cm",
            line_6:"1x Kit Bolinha Pic com Guizo",
            value: 8.90,
        },
        {
            imag:C2223,
            title: "Kit Bolinha Paw com Guizo",
            id:"Núm_00146",
            code:"Cód_C2223",
            line_2:"35Cm",
            line_6:"1x Kit Bolinha Paw com Guizo",
            value: 4.90,
        },
        {
            imag:C2224,
            title: "Kit Bolinha Fish com Guizo",
            id:"Núm_00147",
            code:"Cód_C2224",
            line_2:"35Cm",
            line_6:"1x Kit Bolinha Fish com Guizo",
            value: 5.90,
        },
        {
            imag:C2227,
            title: "Varinha Ratinho + Penas",
            id:"Núm_00148",
            code:"Cód_C2227",
            line_2:"30Cm",
            line_6:"1x Varinha Ratinho + Penas",
            value: 6.90,
        },
        {
            imag:PM1704X,
            title: "Kit Bolinha Benzina com Guizo",
            id:"Núm_00149",
            code:"Cód_PM1704",
            line_2:"3Cm",
            line_6:"1x Kit Bolinha Benzina com Guizo",
            value: 5.90,
        },
        {
            imag:C2232,
            title: "Cat Bit Unitário",
            id:"Núm_00150",
            code:"Cód_C2232",
            line_2:"5Cm",
            line_6:"1x Cat Bit Unitário",
            value: 9.90,
        },
        {
            imag:C2231,
            title: "Varinha Bolinha de Guizo com Penas",
            id:"Núm_00151",
            code:"Cód_C2231",
            line_2:"5Cm",
            line_6:"1x Varinha Bolinha de Guizo com Penas",
            value: 21.58,
        },
        {
            imag:C2229,
            title: "Cat Pomo Unitário",
            id:"Núm_00152",
            code:"Cód_C2229",
            line_2:"15Cm",
            line_6:"1x Varinha Bolinha de Guizo com Penas",
            value: 7.90,
        },
        {
            imag:C2130,
            title: "Cat Guizo Serpentina Unitário",
            id:"Núm_00153",
            code:"Cód_C2130",
            line_2:"15Cm",
            line_6:"1x Cat Guizo Serpentina Unitário",
            value: 1.99,
        },
        {
            imag:C2163,
            title: "Cat HaHaHa",
            id:"Núm_00154",
            code:"Cód_C2163",
            line_2:"5Cm",
            line_6:"1x Cat HaHaHa",
            value: 7.68,
        },
        {
            imag:BR10175XX,
            title: "Bola Cat Transada P",
            id:"Núm_00155",
            code:"Cód_10175",
            line_2:"5Cm",
            line_6:"1x Bola Cat Transada P",
            value: 14.90,
        },
        {
            imag:C2225X,
            title: "Bola Cat Transada M",
            id:"Núm_00156",
            code:"Cód_C2225",
            line_2:"7Cm",
            line_6:"1x Bola Cat Transada M",
            value: 4.90,
        },
        {
            imag:C2230,
            title: "Mini Alteres com Guizo Unitário",
            id:"Núm_00157",
            code:"Cód_C2230",
            line_2:"7Cm",
            line_6:"1x Mini Alteres com Guizo Unitário",
            value: 6.90,
        },
        {
            imag:C2067,
            title: "Cat Guizo Tail Unitário",
            id:"Núm_00158",
            code:"Cód_C2067",
            line_2:"10Cm",
            line_6:"1x Cat Guizo Tail Unitário",
            value: 14.90,
        },
        {
            imag:S5090,
            title: "Kit Bolinha Fish com Guizo",
            id:"Núm_00159",
            code:"Cód_S5090",
            line_2:"15Cm",
            line_6:"1x Kit Bolinha Fish com Guizo",
            value: 29.90,
        },
        {
            imag:C2203,
            title: "Cat Liuxing Unitário",
            id:"Núm_00160",
            code:"Cód_C2203",
            line_2:"15Cm",
            line_6:"1x Cat Liuxing Unitário",
            value: 9.90,
        },
        {
            imag:UZ42,
            title: "Graminha Para Cães",
            id:"Núm_00161",
            code:"Cód_UZ42",
            line_6:"1x Graminha Para Cães",
            value: 8.90,
        },
        {
            imag:"''''UZ44''''",
            title: "Graminha Para Gatos",
            id:"Núm_00162",
            code:"Cód_UZ44",
            line_6:"1x Graminha Para Gatos",
            value: 8.90,
        },
        {
            imag:"''''JV01''''",
            title: "Erva do Gato Cat Nip",
            id:"Núm_00163",
            code:"Cód_UZ44",
            line_6:"1x Erva do Gato Cat Nip",
            value: 4.90,
        },
        {
            imag:"''''010147''''",
            title: "Coleira Cat Perigo",
            id:"Núm_00164",
            code:"Cód_010147",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Perigo",
            value: 9.99,
        },
        {
            imag:"''''010141''''",
            title: "Coleira Cat Caveira",
            id:"Núm_00165",
            code:"Cód_010141",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Caveira",
            value: 9.99,
        },
        {
            imag:"''''010140''''",
            title: "Coleira Cat Cactus",
            id:"Núm_00166",
            code:"Cód_010140",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Cactus",
            value: 9.99,
        },
        {
            imag:"''''010142''''",
            title: "Coleira Cat Donuts",
            id:"Núm_00167",
            code:"Cód_010142",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Donuts",
            value: 9.99,
        },
        {
            imag:"''''010144''''",
            title: "Coleira Cat Floral",
            id:"Núm_00168",
            code:"Cód_010144",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Floral",
            value: 9.99,
        },
        {
            imag:"''''010146''''",
            title: "Coleira Cat Onça",
            id:"Núm_00169",
            code:"Cód_010146",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Onça",
            value: 9.99,
        },
        {
            imag:"''''010143''''",
            title: "Coleira Cat Flamingo",
            id:"Núm_00170",
            code:"Cód_010143",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Flamingo",
            value: 9.99,
        },
        {
            imag:"''''010145''''",
            title: "Coleira Cat Kiwi",
            id:"Núm_00171",
            code:"Cód_010145",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Kiwi",
            value: 9.99,
        },
        {
            imag:"''''010139''''",
            title: "Coleira Cat Arco-Iris",
            id:"Núm_00172",
            code:"Cód_010139",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Arco-Iris",
            value: 9.99,
        },
        {
            imag:"''''010148''''",
            title: "Coleira Cat Xadrez",
            id:"Núm_00173",
            code:"Cód_010148",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Xadrez",
            value: 9.99,
        },
        {
            imag:"''''0010147''''",
            title: "Coleira Cat Perigo",
            id:"Núm_00174",
            code:"Cód_0010147",
            line_6:"1x Coleira Cat Perigo",
            value: 19.99,
        },
        {
            imag:"''''0010141''''",
            title: "Coleira Cat Caveira",
            id:"Núm_00175",
            code:"Cód_0010141",
            line_6:"1x Coleira Cat Caveira",
            value: 19.99,
        },
        {
            imag:"''''0010140''''",
            title: "Coleira Cat Cactus",
            id:"Núm_00176",
            code:"Cód_0010140",
            line_6:"1x Coleira Cat Cactus",
            value: 19.99,
        },
        {
            imag:"''''0010142''''",
            title: "Coleira Cat Donuts",
            id:"Núm_00177",
            code:"Cód_0010142",
            line_6:"1x Coleira Cat Donuts",
            value: 19.99,
        },
        {
            imag:"''''0010144''''",
            title: "Coleira Cat Floral",
            id:"Núm_00178",
            code:"Cód_0010144",
            line_6:"1x Coleira Cat Floral",
            value: 19.99,
        },
        {
            imag:"''''0010146''''",
            title: "Coleira Cat Onça",
            id:"Núm_00179",
            code:"Cód_0010146",
            line_6:"1x Coleira Cat Onça",
            value: 19.99,
        },
        {
            imag:"''''010143''''",
            title: "Coleira Cat Flamingo",
            id:"Núm_00180",
            code:"Cód_010143",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Flamingo",
            value: 19.99,
        },
        {
            imag:"''''010145''''",
            title: "Coleira Cat Kiwi",
            id:"Núm_00181",
            code:"Cód_010145",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Kiwi",
            value: 19.99,
        },
        {
            imag:"''''010139''''",
            title: "Coleira Cat Arco-Iris",
            id:"Núm_00182",
            code:"Cód_010139",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Arco-Iris",
            value: 19.99,
        },
        {
            imag:"''''010148''''",
            title: "Coleira Cat Xadrez",
            id:"Núm_00183",
            code:"Cód_010148",
            line_2:"23 a 35Cm",
            line_6:"1x Coleira Cat Xadrez",
            value: 19.99,
        },
        {
            imag:OB1108,
            title: "Condicionador Cães e Gatos",
            line_1:"PH neutro, para todos os tipos de pelos e tonalidades, promove alinhamento das cuticulas, prolonga o efeito escova, hidratação profunda, auxilia no desembaraço, deposição de ativos, tensoativos balanceados, fragráncia frutada.",
            id:"Núm_00235",
            code:"Cód_OB1108",
            line_2:"700ml",
            line_6:"1x Condicionador Cães e Gatos",
            value: 9.99,
        },
        {
            imag:OB1109,
            title: "Shampoo Gatos",
            inf:"PH neutro, ideal para todos os tipos de pelos e tonalidades, repôe a hidratação perdida contra a oleosidade, suaviza a pele e pelos, deposição de ativos tensoativos balanceados, fragrância inspirada Victoria Secrets Seduction",
            id:"Núm_00236",
            code:"Cód_OB1109",
            line_2:"700ml",
            line_6:"1x Shampoo Gatos",
            value: 9.99,
        },
        // {
            //     imag:PM1577,
            //     title: "Comedouro Osso",
            //     indexId:1,
        //     id:"Núm_00237#055", ref_1:"Cód_PM1507", color_0:"1",
        //     id_2:"Núm_00238#055", ref_2:"Cód_PM----", color_1:"2",
        //     id_3:"Núm_00239#055", ref_3:"Cód_PM----", color_2:"3",
        //     id_4:"Núm_00240#055", ref_4:"Cód_PM----", color_3:"4",
        //     id_5:"Núm_00241#055", ref_5:"Cód_PM----", color_4:"5",
        //     id_6:"Núm_00242#055", ref_6:"Cód_PM----", color_5:"6",
        //     line_2:"",
        //     line_6:"1x Comedouro Osso",
        //     value: 14.12,
        //   },
        //   {
        //     imag:PM1086,
        //     title: "Comedouro Classic 200ML",
        //     indexId:2,
        //     id:"Núm_00243#055", ref_1:"Cód_PM1086", color_0:CC1,
        //     id_2:"Núm_00244#055", ref_2:"Cód_CC2", color_1:CC2,
        //     id_3:"Núm_00245#055", ref_3:"Cód_PM1087", color_2:"3",
        //     id_4:"Núm_00246#055", ref_4:"Cód_PM1090", color_3:"4",
        //     id_5:"Núm_00247#055", ref_5:"Cód_PM1672", color_4:"5",
        //     id_6:"Núm_00248#055", ref_6:"Cód_PM1638", color_5:"6",
        //     id_7:"Núm_00249#055", ref_7:"Cód_PM1639", color_6:"7",
        //     id_8:"Núm_00250#055", ref_8:"Cód_PM1640", color_7:"8",     
        //     line_2:"",
        //     line_6:"1x Comedouro Classic 200ML",
        //     value: 5.16,
        //   },
        {
            imag:PM1577,
            title: "Comedouro Osso 1L",
            id:[["Núm_00237#055", "Núm_00238#055", "Núm_00239#055", "Núm_00240#055", "Núm_00241#055", "Núm_00242#055"],[]],
            code:[["Cód_PM1577", "Cód_PM1578", "Cód_PM1786", "Cód_PM1787", "Cód_PM1788", "Cód_PM1789"],[]],
            color_1:CO1, color_2:CO2, color_3:CO3, color_4:CO4, color_5:CO5, color_6:CO6,
            line_2:"1000 ml",
            line_3:"Plástico polido",
            line_4:"Em formato de osso",
            line_5:"Capacidade de 1000ML",
            line_6:"1x Comedouro Osso 1L",
            value: 14.12,
        },
        {
            imag:PM1086,
            title: "Comedouro Classic",
            measure_1:"200ML", measure_2:"500ML", measure_3:"1050ML", measure_4:"1900ML",
            id:[
                ["Núm_00243#055", "Núm_00244#055", "Núm_00245#055", "Núm_00246#055", "Núm_00247#055", "Núm_00248#055", "Núm_00249#055", "Núm_00250#055"],
                ["Núm_00251#055", "Núm_00252#055", "Núm_00253#055", "Núm_00254#055", "Núm_00255#055", "Núm_00256#055", "Núm_00257#055", "Núm_00258#055"],
                ["Núm_00259#055", "Núm_00260#055", "Núm_00261#055", "Núm_00262#055", "Núm_00263#055", "Núm_00264#055", "Núm_00265#055", "Núm_00266#055"],
                ["Núm_00267#055", "Núm_00268#055", "Núm_00269#055", "Núm_00270#055", "Núm_00271#055", "Núm_00272#055", "Núm_00273#055", "Núm_00274#055"],
            ],
            code:[
                ["Cód_PM1086", "Cód_PM1421", "Cód_PM1087", "Cód_PM1090", "Cód_PM1672", "Cód_PM1638", "Cód_PM1639", "Cód_PM1640"],
                ["Cód_PM1092", "Cód_PM1094", "Cód_PM1093", "Cód_PM1096", "Cód_PM1671", "Cód_PM1635", "Cód_PM1636", "Cód_PM1637"],
                ["Cód_PM1098", "Cód_PM1100", "Cód_PM1099", "Cód_PM1102", "Cód_PM1619", "Cód_PM1620", "Cód_PM1622", "Cód_PM1621"],
                ["Cód_PM1105", "Cód_PM1107", "Cód_PM1106", "Cód_PM1109", "Cód_PM1700", "Cód_PM1632", "Cód_PM1633", "Cód_PM1634"],
            ],
            color_1:CC1, color_2:CC2, color_3:CC3, color_4:CC4, color_5:CC5, color_6:CC6, color_7:CC7, color_8:CC8,
            line_2:"200ml, 500ml, 1050ml, 1900ml",
            line_6:"1x Comedouro Classic x ml",
            value:[5.16, 9.82, 10.20, 13.79],
        },
        // {
        //     imag:PM1082,
        //     title: "",
        //     id:"Núm_0018x",
        //     code:"Cód_PM1082",
        //     line_2:"",
        //     line_6:"1x ",
        //     value: 5.90,
        // },
        // {
        //     imag:PM1083,
        //     title: "",
        //     id:"Núm_0018x",
        //     code:"Cód_PM1083",
        //     line_2:"",
        //     line_6:"1x ",
        //     value: 5.90,
        // },
        // {
        //     imag:PM1424,
        //     title: "",
        //     id:"Núm_0018x",
        //     code:"Cód_PM1424",
        //     line_2:"",
        //     line_6:"1x ",
        //     value: 5.90,
        // },
        // {
        //     imag:PM3668,
        //     title: "",
        //     id:"Núm_0018x",
        //     code:"Cód_PM3668",
        //     line_2:"",
        //     line_6:"1x ",
        //     value: 5.90,
        // },
        // {
        //     imag:EI12,
        //     title: "Sanduiche de Vinil",
        //     id:"Núm_0018x",
        //     code:"Cód_EI12",
        //     line_2:"",
        //     line_6:"1x Sanduiche de Vinil",
        //     value: 6.90,
        // },
    ],
//======================================================================================================//

//======================================================================================================//
    [
        {
            imag:CA10196,
            title:"Arranhador Boston",
            line_1:"Material: MDF,pelúcia e sisal",
            line_2:"(C:30)x(L:40)x(A:60)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 20x20Cm",
            line_4:"Diâmetro do orificio circular do interior: 30Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00028",
            code:"Cód_10196",
            line_6:"1x arranhador Boston",
            value:141.09,   
        },
        {
            imag:OB1108,
            title: "Condicionador Cães e Gatos",
            line_1:"PH neutro, para todos os tipos de pelos e tonalidades, promove alinhamento das cuticulas, prolonga o efeito escova, hidratação profunda, auxilia no desembaraço, deposição de ativos, tensoativos balanceados, fragráncia frutada.",
            id:"Núm_00235",
            code:"Cód_OB1108",
            line_2:"",
            line_6:"1x Condicionador Cães e Gatos",
            value: 9.99,
        },
        {
            imag:"''''UZ42''''",
            title: "Graminha Para Cães",
            id:"Núm_00162",
            code:"Cód_UZ42",
            line_6:"1x Graminha Para Cães",
            value: 8.90,
        },
        {
            imag:BR10281,
            title: "Varinha Borboleta",
            id:"Núm_00129",
            code:"Cód_10281",
            line_2:"35Cm",
            line_6:"1x Varinha borboleta",
            value: 8.90,
        },
        {
            imag:CA10219,
            title:"Arranhador Vênus",
            line_1:"Material: MDF,pelúcia,sisal e manta de juta",
            line_2:"(C:30)x(L:30)x(A:50)Cm",
            line_3:"Diâmetro dos orifícios exteriores: 18Cm",
            line_4:"Diâmetro do orificio circular do interior: 18Cm",
            line_5:"Recomendado: para gatos adultos e filhotes",
            id:"Núm_00014",
            code:"Cód_10219",
            line_6:"1x arranhador Vênus",
            value:89.51,   
        },
        {
            imag:"''''0010144''''",
            title: "Coleira Cat Floral",
            id:"Núm_00180",
            code:"Cód_0010144",
            line_6:"1x Coleira Cat Floral",
            value: 19.99,
        },
        {
            imag:BR10176,
            title: "Varinha Ping Penas",
            id:"Núm_00127",
            code:"Cód_10176",
            line_2:"35Cm",
            line_6:"1x Varinha ping penas",
            value: 5.90,
        },  
    ],
//======================================================================================================//
]
//======================================================================================================//